In [13]:
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

import numpy as np
import pandas as pd

In [2]:
iris = load_iris()

In [4]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
iris.target[:5]

array([0, 0, 0, 0, 0])

In [10]:
X = iris.data
y = iris.target

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
# knn_clf = KNeighborsClassifier()
# knn_clf.fit(X, y)

KNeighborsClassifier()

## 1. K- 폴드 교차 검증

In [25]:
from sklearn.metrics import accuracy_score # 정확도

In [38]:
accuracy_list = []

knn_clf = KNeighborsClassifier()

kfold = KFold(n_splits=5, shuffle=True)
for train_index, valid_index in kfold.split(X):
  # 훈련(학습)
  X_train, y_train = X[train_index], y[train_index] # 4/5
  X_valid, y_valid = X[valid_index], y[valid_index] # 1/5
  knn_clf.fit(X_train, y_train)
  
  
  # 예측과 평가(정확도)
  pred = knn_clf.predict(X_valid)
  accuracy = accuracy_score(y_valid, pred)
  accuracy_list.append(accuracy)

print("평균 정확도 : ", np.mean(accuracy_list))

평균 정확도 :  0.9733333333333334


## 2. Stratified K 폴드 교차 검증

In [39]:
accuracy_list = []

knn_clf = KNeighborsClassifier()

skfold = StratifiedKFold(n_splits=5, shuffle=True)
for train_index, valid_index in skfold.split(X, y):
  # 훈련(학습)
  X_train, y_train = X[train_index], y[train_index] # 4/5
  X_valid, y_valid = X[valid_index], y[valid_index] # 1/5
  knn_clf.fit(X_train, y_train)
  
  
  # 예측과 평가(정확도)
  pred = knn_clf.predict(X_valid)
  accuracy = accuracy_score(y_valid, pred)
  accuracy_list.append(accuracy)

print("평균 정확도 : ", np.mean(accuracy_list))

평균 정확도 :  0.96


## 3. cross_val_score()

In [43]:
from sklearn.model_selection import cross_val_score

knn_clf = KNeighborsClassifier()

#kfold = KFold(n_splits=5, shuffle=True)
skfold = StratifiedKFold(n_splits=5, shuffle=True)

scores = cross_val_score(knn_clf, X, y, scoring="accuracy", cv=skfold) # scoring은 검증 데이터를 어떤 성능 지표로 평가할지

In [44]:
scores

array([0.93333333, 0.9       , 1.        , 1.        , 1.        ])

In [45]:
np.mean(scores)

0.9666666666666668